config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :friendships
  resources :admins
  # devise_for :personrails
  resources :mails
  resources :projects do
    resources :tasks,  only: [:index, :new, :create]
  end
  resources :tasks, only: [:show, :edit, :update, :destroy]
  scope module: 'admin' do
    resources :articles, :comments
  end
  resources :candidates
  resources :session, only: [:create]
  get 'tweets/index'
  get 'tweets/new'
  resources :tweets
  resources :employees
  resources :animals
  resources :books
  resources :authors
  resources :suppliers
  resources :products
  resources :posts #instead of creating each method route for posts separately, we can use this
  root 'posts#index' #now this view will load at start
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_many :friendships
  has_many :friends, :through => :friendships
end

app/models/animal.rb
class Animal < ApplicationRecord

  validates :age, inclusion: 1...10 #validates only if age between 1 and 9
  validates :name, length: { minimum: 2 }, uniqueness: { message: ->(object, data) do
    "Hey #{object.name}, #{data[:value]} is already taken."
  end }
  validates :bio, presence: true
  validates :email, presence: true, format: { with: /.*@.*/ }, confirmation: true
end

app/models/bike.rb
class Bike < Vehicle
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, counter_cache: true
  scope :created_yesterday, -> { where(['created_at >= ?', Book::PARAM[:created_at]]) }
  scope :created_whenever, ->(date = DateTime.now - 1.day) { where(['created_at >= ?', date]) }

  PARAM = {
    created_at: DateTime.now - 1.day,
    updated_at: Time.current - 1.day
  }

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :engineer, dependent: :nullify
end

app/models/cycle.rb
class Cycle < Vehicle
end

app/models/game.rb
class Game < ApplicationRecord
  has_one :peak
  has_one :team, through: :peak
end

app/models/guest.rb
class Guest < Customer
  def guest?
    true
  end

  def name
    'Guest'
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :worker

  after_destroy :log_destroy_job

  def log_destroy_job
    puts 'Job destroyed'
  end
end

app/models/mail.rb
class Mail < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :notable, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :card_number, presence: true, if: :paid_with_card?

  def paid_with_card?
    payment_type == 'card'
  end
end

app/models/part.rb
class Part < ApplicationRecord
  has_and_belongs_to_many :assemblies
end

app/models/peak.rb
class Peak < ApplicationRecord
  belongs_to :game
  has_one :team
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: %i[draft published idk]
  enum super_post: { is_super: 0, is_not_super: 1 }
  enum archive: { is_archive: 1, is_not_archive: 0 }

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/table.rb
class Table < ApplicationRecord
  validate :legs_must_be_4
  validates_with TopValidator
  validates :material, { type: true }

  private
  def legs_must_be_4
    if legs.present? && legs != 4
      errors.add(:legs, "must be 4")
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :projects
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :peak
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friends, class_name: 'Friend'
  has_many :emergencies, class_name: 'Emergency'
  with_options if: :is_admin? do |admin|
    admin.validates :password, length: { minimum: 10 }
    admin.validates :email, presence: true
  end

  after_initialize do |user|
    puts "You have initialized an object! #{user}"
  end

  after_find do |user|
    puts "You have found an object! #{user}"
  end
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.email %></td>
        <td><%= admin.password %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "Add Friend", friendships_path(:friend_id => admin), :method => :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/shared/_post.html.erb
<h2><%= post.title %></h2>
<div> <%= truncate(post.body, :length => 35) %></div>
<%= link_to "Read Post", post%>

app/views/shared/_spacer.html.erb
<p>I am a divider</p>
<hr/>