config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :friendships
  resources :admins
  # devise_for :personrails
  resources :mails
  resources :projects do
    resources :tasks,  only: [:index, :new, :create]
  end
  resources :tasks, only: [:show, :edit, :update, :destroy]
  scope module: 'admin' do
    resources :articles, :comments
  end
  resources :candidates
  resources :session, only: [:create]
  get 'tweets/index'
  get 'tweets/new'
  resources :tweets
  resources :employees
  resources :animals
  resources :books
  resources :authors
  resources :suppliers
  resources :products
  resources :posts #instead of creating each method route for posts separately, we can use this
  root 'posts#index' #now this view will load at start
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_many :friendships
  has_many :friends, :through => :friendships
end

app/models/animal.rb
class Animal < ApplicationRecord

  validates :age, inclusion: 1...10 #validates only if age between 1 and 9
  validates :name, length: { minimum: 2 }, uniqueness: { message: ->(object, data) do
    "Hey #{object.name}, #{data[:value]} is already taken."
  end }
  validates :bio, presence: true
  validates :email, presence: true, format: { with: /.*@.*/ }, confirmation: true
end

app/models/bike.rb
class Bike < Vehicle
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, counter_cache: true
  scope :created_yesterday, -> { where(['created_at >= ?', Book::PARAM[:created_at]]) }
  scope :created_whenever, ->(date = DateTime.now - 1.day) { where(['created_at >= ?', date]) }

  PARAM = {
    created_at: DateTime.now - 1.day,
    updated_at: Time.current - 1.day
  }

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :engineer, dependent: :nullify
end

app/models/cycle.rb
class Cycle < Vehicle
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :admin
  belongs_to :buddy, :class_name => 'Admin'
end

app/models/game.rb
class Game < ApplicationRecord
  has_one :peak
  has_one :team, through: :peak
end

app/models/guest.rb
class Guest < Customer
  def guest?
    true
  end

  def name
    'Guest'
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :worker

  after_destroy :log_destroy_job

  def log_destroy_job
    puts 'Job destroyed'
  end
end

app/models/mail.rb
class Mail < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :notable, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :card_number, presence: true, if: :paid_with_card?

  def paid_with_card?
    payment_type == 'card'
  end
end

app/models/part.rb
class Part < ApplicationRecord
  has_and_belongs_to_many :assemblies
end

app/models/peak.rb
class Peak < ApplicationRecord
  belongs_to :game
  has_one :team
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: %i[draft published idk]
  enum super_post: { is_super: 0, is_not_super: 1 }
  enum archive: { is_archive: 1, is_not_archive: 0 }

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/table.rb
class Table < ApplicationRecord
  validate :legs_must_be_4
  validates_with TopValidator
  validates :material, { type: true }

  private
  def legs_must_be_4
    if legs.present? && legs != 4
      errors.add(:legs, "must be 4")
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :projects
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :peak
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friends, class_name: 'Friend'
  has_many :emergencies, class_name: 'Emergency'
  with_options if: :is_admin? do |admin|
    admin.validates :password, length: { minimum: 10 }
    admin.validates :email, presence: true
  end

  after_initialize do |user|
    puts "You have initialized an object! #{user}"
  end

  after_find do |user|
    puts "You have found an object! #{user}"
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: %i[ show edit update destroy ]

  # GET /friendships or /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1 or /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships or /friendships.json
  def create
    # @friendship = Friendship.new(friendship_params)
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: "Added Friend." }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1 or /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: "Friendship was successfully updated." }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1 or /friendships/1.json
  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to friendships_url, notice: "Friendship was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friendship_params
      params.require(:friendship).permit(:admin_id, :friend_id, :create, :destroy)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_with(model: friendship, local: true) do |form| %>
  <% if friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :admin_id %>
    <%= form.number_field :admin_id %>
  </div>

  <div class="field">
    <%= form.label :friend_id %>
    <%= form.number_field :friend_id %>
  </div>

  <div class="field">
    <%= form.label :create %>
    <%= form.text_field :create %>
  </div>

  <div class="field">
    <%= form.label :destroy %>
    <%= form.text_field :destroy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friendships</h1>

<table>
  <thead>
    <tr>
      <th>Admin</th>
      <th>Friend</th>
      <th>Create</th>
      <th>Destroy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.admin_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.create %></td>
        <td><%= friendship.destroy %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admin:</strong>
  <%= @friendship.admin_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Create:</strong>
  <%= @friendship.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @friendship.destroy %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>