config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :friendships
  resources :admins
  # devise_for :personrails
  resources :mails
  resources :projects do
    resources :tasks,  only: [:index, :new, :create]
  end
  resources :tasks, only: [:show, :edit, :update, :destroy]
  scope module: 'admin' do
    resources :articles, :comments
  end
  resources :candidates
  resources :session, only: [:create]
  get 'tweets/index'
  get 'tweets/new'
  resources :tweets
  resources :employees
  resources :animals
  resources :books
  resources :authors
  resources :suppliers
  resources :products
  resources :posts #instead of creating each method route for posts separately, we can use this
  root 'posts#index' #now this view will load at start
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_many :friendships
  has_many :friends, :through => :friendships
end

app/models/animal.rb
class Animal < ApplicationRecord

  validates :age, inclusion: 1...10 #validates only if age between 1 and 9
  validates :name, length: { minimum: 2 }, uniqueness: { message: ->(object, data) do
    "Hey #{object.name}, #{data[:value]} is already taken."
  end }
  validates :bio, presence: true
  validates :email, presence: true, format: { with: /.*@.*/ }, confirmation: true
end

app/models/author.rb
include Extension
class Author < ApplicationRecord
  has_many :books, dependent: :destroy, autosave: true,
              before_add: :my_before_add, after_add: :my_after_add,
             before_remove: :my_before_remove, after_remove: :my_after_remove
  validates_associated :books

  has_many :books, -> { extending FindRecentExtension }


  private

  def my_before_add(book)
    puts 'I am in before add'
  end

  def my_after_add(book)
    puts 'I am in after add'
  end

  def my_before_remove(book)
    puts 'I am in before remove'
  end

  def my_after_remove(book)
    puts 'I am in after remove'
  end
end

app/models/bike.rb
class Bike < Vehicle
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, counter_cache: true
  scope :created_yesterday, -> { where(['created_at >= ?', Book::PARAM[:created_at]]) }
  scope :created_whenever, ->(date = DateTime.now - 1.day) { where(['created_at >= ?', date]) }

  PARAM = {
    created_at: DateTime.now - 1.day,
    updated_at: Time.current - 1.day
  }

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :engineer, dependent: :nullify
end

app/models/cycle.rb
class Cycle < Vehicle
end

app/models/game.rb
class Game < ApplicationRecord
  has_one :peak
  has_one :team, through: :peak
end

app/models/guest.rb
class Guest < Customer
  def guest?
    true
  end

  def name
    'Guest'
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :worker

  after_destroy :log_destroy_job

  def log_destroy_job
    puts 'Job destroyed'
  end
end

app/models/mail.rb
class Mail < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :notable, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :card_number, presence: true, if: :paid_with_card?

  def paid_with_card?
    payment_type == 'card'
  end
end

app/models/part.rb
class Part < ApplicationRecord
  has_and_belongs_to_many :assemblies
end

app/models/peak.rb
class Peak < ApplicationRecord
  belongs_to :game
  has_one :team
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: %i[draft published idk]
  enum super_post: { is_super: 0, is_not_super: 1 }
  enum archive: { is_archive: 1, is_not_archive: 0 }

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/table.rb
class Table < ApplicationRecord
  validate :legs_must_be_4
  validates_with TopValidator
  validates :material, { type: true }

  private
  def legs_must_be_4
    if legs.present? && legs != 4
      errors.add(:legs, "must be 4")
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :projects
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :peak
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friends, class_name: 'Friend'
  has_many :emergencies, class_name: 'Emergency'
  with_options if: :is_admin? do |admin|
    admin.validates :password, length: { minimum: 10 }
    admin.validates :email, presence: true
  end

  after_initialize do |user|
    puts "You have initialized an object! #{user}"
  end

  after_find do |user|
    puts "You have found an object! #{user}"
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]

  # GET /animals or /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1 or /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: "Animal was successfully created." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: "Animal was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Animal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:name, :age, :bio, :email)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Bio</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.name %></td>
        <td><%= animal.age %></td>
        <td><%= animal.bio %></td>
        <td><%= animal.email %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @animal.age %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @animal.bio %>
</p>

<p>
  <strong>Email:</strong>
  <%= @animal.email %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>